name: Github actions with tsc and vite build and deploy
on: 
  push:
    branches: 
    - main
jobs:
  Do-the-travis-thing:
    runs-on: ubuntu-20.04 

    strategy:
      matrix:
        node-version: [18.x] # We will deploy with only one version of node  

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm build
        run: |
              npm run build --if-present
      - name: deploy to droplet
        run: scp -r ./dist/* root@${{ secrets.DROPLET_URL }}:/var/www/${{ secrets.PROJECT_NAME }}